from pptx import Presentation
from pptx.util import Inches, Pt
from fpdf import FPDF
import os
import re
from docx import Document
from docx.shared import Pt
import json
import google.genai as genai
from google.genai import types

# --- Font manager for PDF ---
def get_pdf_font(language="en", ttf_path=r"C:\Users\ssmat\Downloads\ai_course_creator - Copy\ai_course_creator\DejaVuSans.ttf"):
    """
    Returns the font name for PDF based on language.
    Falls back to built-in if TTF not found.
    """
    language = language.lower()
    if language in ["zh", "chinese", "zh-cn"]:
        return "STSong-Light"  # FPDF does not support CID fonts; if needed, use ReportLab
    elif language in ["ja", "japanese"]:
        return "HeiseiMin-W3"
    elif language in ["ko", "korean"]:
        return "HYSMyeongJo-Medium"
    else:
        if os.path.exists(ttf_path):
            return ttf_path
        return None  # fallback to default Arial

# --- PDF class ---
class PDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 12)
        self.cell(0, 10, 'AI Course Creator', 0, 1, 'C')

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

# --- Create PDF ---
def create_pdf(course_content, topic, language="en"):
    """Creates a PDF document from the course content."""
    pdf = PDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    font_file = get_pdf_font(language)
    if font_file:
        pdf.add_font('CustomFont', '', font_file, uni=True)
        pdf.set_font('CustomFont', '', 12)
    else:
        pdf.set_font('Arial', '', 12)

    pdf.set_font_size(24)
    pdf.cell(0, 20, course_content.get('course_title', topic), 0, 1, 'C')
    pdf.ln(10)

    for module in course_content.get('modules', []):
        pdf.set_font_size(18)
        pdf.cell(0, 15, module.get('module_title', 'Module'), 0, 1, 'L')
        pdf.ln(5)

        for lesson in module.get('lessons', []):
            pdf.set_font_size(14)
            pdf.cell(0, 10, lesson.get('lesson_title', 'Lesson'), 0, 1, 'L')

            pdf.set_font_size(12)
            content = lesson.get('content', '')
            content = content.encode('ascii', 'ignore').decode('ascii')  # remove unsupported chars for FPDF
            pdf.multi_cell(0, 10, content)
            pdf.ln(10)

    filepath = f"{topic.replace(' ', '_').lower()}_course.pdf"
    pdf.output(filepath)
    return filepath


MODEL_NAME = 'gemini-2.5-flash'
api_key = os.getenv("GEMINI_API_KEY") or os.getenv("GOOGLE_API_KEY")
if not api_key:
    raise ValueError("API Key not found. Please set the GEMINI_API_KEY or GOOGLE_API_KEY environment variable.")
client = genai.Client(api_key=api_key)

def create_ppt(course_content, topic, language="en"):
    """Creates a PowerPoint presentation from the course content with AI-summarized key points."""
    prs = Presentation()

    # Title Slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    slide.shapes.title.text = course_content.get('course_title', topic)
    slide.placeholders[1].text = "Generated by AI Course Creator"

    content_slide_layout = prs.slide_layouts[1]

    # Choose font for PPT
    if language.lower() in ["zh", "chinese", "zh-cn"]:
        ppt_font = "SimSun"
    elif language.lower() in ["ja", "japanese"]:
        ppt_font = "MS Mincho"
    elif language.lower() in ["ko", "korean"]:
        ppt_font = "Malgun Gothic"
    else:
        ppt_font = "DejaVu Sans"

    for module_idx, module in enumerate(course_content.get('modules', []), start=1):
        for lesson_idx, lesson in enumerate(module.get('lessons', []), start=1):
            lesson_number = f"{module_idx}.{lesson_idx}"
            lesson_title = lesson.get('lesson_title', 'Lesson')
            lesson_content = lesson.get('content', '')

            # --- Inline Gemini summarization ---
            try:
                prompt = f"""
                Summarize the following lesson content into up to 5 concise key points,
                covering basics, core concepts, and implementation.
                Output strictly as a JSON array of strings. Language: {language}.

                Lesson Content:
                {lesson_content}
                """
                response = client.models.generate_content(
                    model=MODEL_NAME,
                    contents=prompt,
                    config=types.GenerateContentConfig(
                        response_mime_type="application/json"
                    )
                )
                key_points = json.loads(response.text)
                if not isinstance(key_points, list):
                    key_points = lesson_content.split('.')[:5]  # fallback
            except Exception as e:
                print(f"Gemini summarization failed for lesson {lesson_title}: {e}")
                key_points = lesson_content.split('.')[:5]  # fallback

            # Limit slides to max 4 per lesson
            max_slides = 2
            slides_needed = min(max_slides, len(key_points))
            points_per_slide = max(1, len(key_points) // slides_needed)

            for slide_idx in range(slides_needed):
                start_idx = slide_idx * points_per_slide
                end_idx = start_idx + points_per_slide
                slide_points = key_points[start_idx:end_idx]

                slide = prs.slides.add_slide(content_slide_layout)
                slide_title = f"{lesson_number}: {lesson_title}"
                if slides_needed > 1:
                    slide_title += f" (Part {slide_idx + 1})"
                slide.shapes.title.text = slide_title

                body = slide.placeholders[1]
                body.text_frame.clear()
                for point in slide_points:
                    p = body.text_frame.add_paragraph()
                    p.text = f"• {point}"
                    p.font.name = ppt_font
                    p.font.size = Pt(16)
                    p.space_after = Pt(5)

    filepath = f"{topic.replace(' ', '_').lower()}_presentation.pptx"
    prs.save(filepath)
    return filepath


def create_quiz_word(quiz_data, topic):
    doc = Document()

    # Title
    title = doc.add_heading(level=0)
    run = title.add_run(f"Quiz: {topic}")
    run.font.name = "DejaVu Sans"
    run.font.size = Pt(24)
    doc.add_paragraph("\n")

    # Questions
    for idx, question in enumerate(quiz_data.get("quiz", []), start=1):
        q_text = f"{idx}. {question.get('question','')}"
        p = doc.add_paragraph(q_text)
        p.runs[0].font.name = "DejaVu Sans"
        p.runs[0].font.size = Pt(12)

        # Options
        options = question.get("options", [])
        for opt_idx, opt in enumerate(options, start=1):
            opt_text = f"    {chr(64 + opt_idx)}. {opt}"  # A., B., C., D.
            p_opt = doc.add_paragraph(opt_text)
            p_opt.runs[0].font.name = "DejaVu Sans"
            p_opt.runs[0].font.size = Pt(12)

        doc.add_paragraph("\n")

    # Save to downloads folder
    if not os.path.exists("downloads"):
        os.makedirs("downloads")

    filepath = os.path.join("downloads", f"{topic.replace(' ','_').lower()}_quiz.docx")
    doc.save(filepath)
    return filepath


def create_video_scripts_docx(video_scripts_data, course_name):
    downloads_folder = "downloads"
    os.makedirs(downloads_folder, exist_ok=True)

    doc = Document()
    doc.add_heading(course_name, 0)

    for lesson in video_scripts_data.get("videos", []):
        lesson_title = lesson.get("lesson_title", "Lesson")
        doc.add_heading(lesson_title, level=1)

        for video in lesson.get("video_links", []):
            script_type = video.get("type", "AI Script")
            doc.add_heading(script_type, level=2)

            script_content = video.get("script_content", [])
            for segment in script_content:
                time = segment.get("time", "")
                narration = segment.get("audio_narration", "")
                visuals = segment.get("visuals", "")

                doc.add_paragraph(f"Time: {time}")
                doc.add_paragraph(f"Narration: {narration}")
                doc.add_paragraph(f"Visuals: {visuals}")
                doc.add_paragraph("")  # Empty line for spacing

            # Include audio file info in doc
            audio_file = video.get("audio_file")
            if audio_file:
                doc.add_paragraph(f"Audio File: {audio_file}")

    # Safe file name
    safe_course = re.sub(r'[^a-zA-Z0-9_-]', '', course_name.replace(" ", "_").lower())
    filepath = os.path.join(downloads_folder, f"{safe_course}_video_scripts.docx")
    doc.save(filepath)
    return filepath